import type { Metadata } from "next";
import "./globalTheme.css";
import Header from "@/assets/components/Header";
import * as fontCss from "@/app/font.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontCss.fontText}>
        <Header />
        {children}
      </body>
    </html>
  );
}
